[package]
name = "protojson"
version = "0.1.0"
authors = ["Doug Woos <doug.woos@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
protobuf = "2.6"
serde-protobuf = "0.8.1"
serde_json = "1.0"
failure = "0.1.5"
serde-value = "0.6"

[build-dependencies]
protobuf-codegen-pure = "2.6"
